contact_links:
  - name: Are you experiencing a bug with a specific extension? Please open an issue in the extension's repository.
    url: https://github.com/zed-industries/extensions/tree/main/extensions
